# Generated by Django 4.0 on 2023-12-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp',
            name='budget',
        ),
    ]
